### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by keirlawson** [gemini-hlsw/gsp-graphql#104]
Would be great to have Scala 3 support for this library, though I'm not sure what would be required to do this, as there are no macros presently I guess this might be fairly straightforward?

**Comment by milessabin** [comment]
Should be. The generic module has a shapeless-2 dependency which could be replaced (source-incompatibly) with shapeless-3 for Scala 3. I'm not sure where doobie is wrt Scala 3 ... @tpolecat?

**Comment by tpolecat** [comment]
doobie and skunk are both up to date and available for Scala 3, so this is probably doable
