### ISSUE TITLE
"sbt docs/previewSite" fails with missing directory

### ISSUE THREAD

**Issue by NigeWarren** [gemini-hlsw/gsp-graphql#151]
On cloning and following the readme - "sbt docs/previewSite" fails with 

[error] java.lang.RuntimeException: Error writing content for page tutorial/in-memory-model.html: Unknown snippet [/Users/Nige/GeminiWorkspace/gsp-graphql/demo/src/main/scala-2/starwars/StarWarsData.scala (No such file or directory)] referenced from [tutorial/in-memory-model.html]

Suspect that "-2" is being added to the "scala" directory ("scala-2"  not being a directory) as a part of support for Scala 3 in sbt - possibly ?

I would attempt a fix but I don't want to bump into the "sbt furniture" resulting in further broken assumptions later.

Nige

**Comment by milessabin** [comment]
Thanks for the report!

**Comment by tpolecat** [comment]
(I just fixed this.)
