### ISSUE TITLE
Limit nodes sometimes not compiled into SQL

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/gsp-graphql#184]
In the test titled `"root limit"` [here](https://github.com/gemini-hlsw/gsp-graphql/blob/main/modules/sql/src/test/scala/SqlFilterLimitOrderBySpec.scala#L553-L614) the `Limit` node introduced during elaboration [here](https://github.com/gemini-hlsw/gsp-graphql/blob/main/modules/skunk/src/test/scala/filterlimitorderby/FilterLimitOrderByData.scala#L168) is not compiled into SQL, which results in over-fetching of rows that are later discarded on the client side (`stripFilters` [here](https://github.com/gemini-hlsw/gsp-graphql/blob/main/modules/sql/src/main/scala/SqlMapping.scala#L144-L170) does not eliminate the `Limit` node). So the tests pass due to luck, but the generated SQL is not as expected. What we see is:

```sql
(
  SELECT listb.b_elem, listb.id, root.id, (NULL :: varchar), (NULL :: varchar)
  FROM root 
  LEFT JOIN listb ON (listb.root_id = root.id)
) UNION ALL (
  SELECT (NULL :: int4), (NULL :: varchar), root.id, lista.a_elem, lista.id 
  FROM root
  LEFT JOIN lista ON (lista.root_id = root.id)
)
```

which has no `LIMIT` clause. 

So there's something wrong in the SQL compiler that's preventing the `LIMIT` clause from being generated. The same issue likely exists for `OFFSET`, which is a bigger problem because `Offset` nodes _must_ be eliminated (we can't rely on client-side logic to save us).

This should be fixed by work @milessabin is doing right now.

**Comment by milessabin** [comment]
Fixed in #152 and #188.
