### ISSUE TITLE
Combine Filter, Offset, Limit, and OrderBy constructors

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/gsp-graphql#185]
Right now a `Query` that contains any combination of `Filter`, `Offset`, `Limit`, and `OrderBy` must specify them in a particular nesting order, otherwise the `QueryInterpreter` will compute incorrect results (and `SqlMapping` will fail with a runtime error). Obviously this is error-prone. We can fix this by combining them into a single constructor, possibly with a builder to allow incremental construction.

**Comment by milessabin** [comment]
Whilst there is a typical nesting of the terms (`Filter`, `OrderBy`, `Offset` then `Limit`) any other ordering are legal, they just specify different (possibly unexpected) behaviour. We now have a `FilterOrderByOffsetLimit` object with `apply` and `unapply` methods which capture the typical nesting.
