### ISSUE TITLE
Update doc site and demo

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#194]
+ The documentation site needs sections added for DB-backed and other mappings.
+ The demo app should have an DB-backed example, possibly and DB-based version of the Star Wars example, or maybe using the world dataset as in the tests.
+ The documentation site needs to be published somewhere (probably Github pages)
+ We should get hold of a suitable domain name (grackle.io and grackle.org both appear to be taken)

**Comment by armanbilge** [comment]
> * The documentation site needs to be published somewhere (probably Github pages)

The sbt-typelevel-site plugin can automate this. https://typelevel.org/sbt-typelevel/site.html

**Comment by armanbilge** [comment]
I've started a branch migrating the docs, but bumped into a couple issues. So it may take a little while to land.

**Comment by milessabin** [comment]
@rpiotrow added some documentation and a demo for a db backed model. More is always better, but I think we have enough to go for a 1.0.0-RC1.

@armanbilge I'm keen to move this to sbt-typelevel-site ... is that something that should be done before or after moving the repo to the Typelevel org?

**Comment by milessabin** [comment]
Moving the sbt-typelevel-site work to #419 and declaring victory on this one.
