### ISSUE TITLE
Set up Scala Steward

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#195]
Probably ought to wait for (#193).

**Comment by armanbilge** [comment]
This repo is now under the care of [lucuma-steward](https://github.com/apps/lucuma-steward).

**Comment by milessabin** [comment]
We'll want to move to the Typelevel instance when the project moves to the TL org (#193). I'll update that issue to mention that we'll need to revisit this then.

**Comment by milessabin** [comment]
Typelevel Scala steward addition done in https://github.com/typelevel/steward/pull/42.
