### ISSUE TITLE
Add support for mutation

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#27]
See [6.2.2](https://graphql.github.io/graphql-spec/June2018/#sec-Mutation).

**Comment by keuhdall** [comment]
Hi, what is the current state of mutations ?
I see https://github.com/gemini-hlsw/gsp-graphql/pull/127 has been merged, is the feature complete and if so, would it be possible to have some mutation examples added in the `demo` module and/or the documentation ?
Thank you !

**Comment by milessabin** [comment]
This has been in place for quite some time now ... this ticket should have been closed.

Right now the only examples are in the tests,

+ [Mutation of a cats-effect `Ref`](https://github.com/gemini-hlsw/gsp-graphql/blob/main/modules/core/src/test/scala/subscription/SubscriptionSpec.scala)
+ [Mutation of database state](https://github.com/gemini-hlsw/gsp-graphql/blob/main/modules/sql/src/test/scala/SqlMutationMapping.scala)

We certainly need more documentation.
