### ISSUE TITLE
Support more sophisticated joins in the doobie module

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#37]
Currently we only compute joins up until the point that we hit a select that through a type that we've already visited (ie. we pass through a recursion point in the schema). If we hit such a select the query will be split into two or more sequential queries. We might be able to avoid this by computing more sophisticated joins.

**Comment by tpolecat** [comment]
A starting point here is to alias tables as they're introduced and use qualified column names. Thread a counter through with `State` or something.

**Comment by milessabin** [comment]
Fixed in #152 and #188.
